
version: '3'
networks:
  queue:
    external: true

services:
  web:
    build: .
    volumes:
      - .:/app
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./supervisord.conf:/etc/supervisord.conf
    depends_on:
      - db
    networks:
      - queue
  
  db:
    image: postgres:10-alpine
    restart: always
    environment:
      POSTGRES_USER: queue
      POSTGRES_DB: queue

    networks:
      - queue
